// <auto-generated />
using System;
using HospitalAdmissionsApp.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalAdmissionsApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HospitalAdmissionsDbContext))]
    partial class HospitalAdmissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.BodyPart", b =>
                {
                    b.Property<Guid>("BodyPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeissCode")
                        .HasColumnType("int");

                    b.HasKey("BodyPartId");

                    b.ToTable("BodyParts");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Diagnosis", b =>
                {
                    b.Property<Guid>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BodyPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiagnosisNameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.DiagnosisName", b =>
                {
                    b.Property<Guid>("DiagnosisNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeissCode")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisNameId");

                    b.ToTable("DiagnosisNames");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.EmergencyVisit", b =>
                {
                    b.Property<Guid>("EmergencyVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPSCCaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmergencyVisitEndingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InjuryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmergencyVisitId");

                    b.ToTable("EmergencyVisits");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.EmergencyVisitEnding", b =>
                {
                    b.Property<Guid>("EmergencyVisitEndingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmergencyVisitEndingId");

                    b.ToTable("EmergencyVisitEndings");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Ethnicity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeissCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Ethnicities");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.FireInvolvementLevel", b =>
                {
                    b.Property<Guid>("FireInvolvementLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeissCode")
                        .HasColumnType("int");

                    b.HasKey("FireInvolvementLevelId");

                    b.ToTable("FireInvolvementLevels");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Hospital", b =>
                {
                    b.Property<Guid>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HospitalStratumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.HospitalAdmission", b =>
                {
                    b.Property<Guid>("HospitalAdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalAdmissionId");

                    b.ToTable("HospitalAdmissions");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.HospitalStratum", b =>
                {
                    b.Property<Guid>("HospitalStratumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalStratumId");

                    b.ToTable("HospitalStrata");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Injury", b =>
                {
                    b.Property<Guid>("InjuryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlcoholInvolvement")
                        .HasColumnType("bit");

                    b.Property<bool>("DrugInvolvement")
                        .HasColumnType("bit");

                    b.Property<Guid>("FireInvolvementLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InjuryId");

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeissCode")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InjuryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeissCode")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("InjuryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Ethnicity", b =>
                {
                    b.HasOne("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Person", null)
                        .WithMany("Ethnicities")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Product", b =>
                {
                    b.HasOne("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Injury", null)
                        .WithMany("ProductsInvolved")
                        .HasForeignKey("InjuryId");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Injury", b =>
                {
                    b.Navigation("ProductsInvolved");
                });

            modelBuilder.Entity("HospitalAdmissionsApp.Infrastructure.Persistence.DataEntities.Person", b =>
                {
                    b.Navigation("Ethnicities");
                });
#pragma warning restore 612, 618
        }
    }
}
